<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

$currDir = dirname(__FILE__);
include("$currDir/defaultLang.php");
include("$currDir/language.php");
include("$currDir/lib.php");
@include("$currDir/hooks/rooms.php");
include("$currDir/services_dml.php");

// mm: can the current member access this page?
$perm = getTablePermissions('services');
if (!$perm[0]) {
	echo error_message($Translation['tableAccessDenied'], false);
	echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
	exit;
}

$x = new DataList;
$x->TableName = "services";

// Fields that can be displayed in the table view
$x->QueryFieldsTV = array(
	"`services`.`id`" => "id",
	"`services`.`name`" => "name",
	"`services`.`cost`" => "cost",
	"`services`.`rate`" => "rate"
);
// mapping incoming sort by requests to actual query fields
$x->SortFields = array(
	1 => '`services`.`id`',
	2 => '`services`.`cost`',
	3 => '`services`.`rate`',
);

// Fields that can be displayed in the csv file
$x->QueryFieldsCSV = array(
	"`services`.`id`" => "id",
	"`services`.`name`" => "name",
	"`services`.`cost`" => "cost",
	"`services`.`rate`" => "rate"
);
// Fields that can be filtered
$x->QueryFieldsFilters = array(
	"`services`.`id`" => "id",
	"`services`.`name`" => "name",
	"`services`.`cost`" => "cost",
	"`services`.`rate`" => "rate"
);

// Fields that can be quick searched
$x->QueryFieldsQS = array(
	"`services`.`id`" => "id",
	"`services`.`name`" => "name",
	"`services`.`cost`" => "cost",
	"`services`.`rate`" => "rate"
);

// Lookup fields that can be used as filterers
$x->filterers = array();

$x->QueryFrom = 'services';
$x->QueryWhere = '';
$x->QueryOrder = '';

$x->AllowSelection = 1;
$x->HideTableView = ($perm[2] == 0 ? 1 : 0);
$x->AllowDelete = $perm[4];
$x->AllowMassDelete = true;
$x->AllowInsert = $perm[1];
$x->AllowUpdate = $perm[3];
$x->SeparateDV = 1;
$x->AllowDeleteOfParents = 0;
$x->AllowFilters = 1;
$x->AllowSavingFilters = 1;
$x->AllowSorting = 1;
$x->AllowNavigation = 1;
$x->AllowPrinting = 1;
$x->AllowCSV = 1;
$x->RecordsPerPage = 10;
$x->QuickSearch = 1;
$x->QuickSearchText = $Translation["quick search"];
$x->ScriptFileName = "services_view.php";
$x->RedirectAfterInsert = "services_view.php?SelectedID=#ID#";
$x->TableTitle = "Services";
$x->TableIcon = "resources/table_icons/building.png";
$x->PrimaryKey = "`services`.`id`";

$x->ColWidth   = array(150, 150, 150);
$x->ColCaption = array("Service Name", "Service Cost", "Service Rate");
$x->ColFieldName = array('name', 'cost', 'rate');
$x->ColNumber  = array(2, 3, 4);

// template paths below are based on the app main directory
$x->Template = 'templates/services_templateTV.html';
$x->SelectedTemplate = 'templates/services_templateTVS.html';
$x->TemplateDV = 'templates/services_templateDV.html';
$x->TemplateDVP = 'templates/services_templateDVP.html';

$x->ShowTableHeader = 1;
$x->TVClasses = "";
$x->DVClasses = "";
$x->HighlightColor = '#FFF0C2';

// mm: build the query based on current member's permissions
$DisplayRecords = $_REQUEST['DisplayRecords'];
if (!in_array($DisplayRecords, array('user', 'group'))) {
	$DisplayRecords = 'all';
}

if ($perm[2] == 1 || ($perm[2] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
	$x->QueryFrom .= ', membership_userrecords';
	$x->QueryWhere = "where `services`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='rooms' and lcase(membership_userrecords.memberID)='" . getLoggedMemberID() . "'";
} elseif ($perm[2] == 2 || ($perm[2] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
	$x->QueryFrom .= ', membership_userrecords';
	$x->QueryWhere = "where `services`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='rooms' and membership_userrecords.groupID='" . getLoggedGroupID() . "'";
} elseif ($perm[2] == 3) { // view all
	// no further action
} elseif ($perm[2] == 0) { // view none
	$x->QueryFields = array("Not enough permissions" => "NEP");
	$x->QueryFrom = '`services`';
	$x->QueryWhere = '';
	$x->DefaultSortField = '';
}
// hook: services
$render = TRUE;
if (function_exists('services_init')) {
	$args = array();
	$render = services_init($x, getMemberInfo(), $args);
}

if ($render) $x->Render();

// hook: rooms_header
$headerCode = '';
if (function_exists('rooms_header')) {
	$args = array();
	$headerCode = rooms_header($x->ContentType, getMemberInfo(), $args);
}
if (!$headerCode) {
	include_once("$currDir/header.php");
} else {
	ob_start();
	include_once("$currDir/header.php");
	$dHeader = ob_get_contents();
	ob_end_clean();
	echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
}

echo $x->HTML;
// hook: rooms_footer
$footerCode = '';
if (function_exists('rooms_footer')) {
	$args = array();
	$footerCode = rooms_footer($x->ContentType, getMemberInfo(), $args);
}
if (!$footerCode) {
	include_once("$currDir/footer.php");
} else {
	ob_start();
	include_once("$currDir/footer.php");
	$dFooter = ob_get_contents();
	ob_end_clean();
	echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
}
